name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
        
      - name: Send Rebuild Request to Portainer
        env:
          PORTAINER_TOKEN: ${{ secrets.PORTAINER_TOKEN }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_MAIN }}
        run: |
          curl -X POST \
                -H "Authorization: Bearer $PORTAINER_TOKEN" \
                -H "Content-Type: application/json" \
                $WEBHOOK_SECRET